USE contagion_db;

TRUNCATE disease;
TRUNCATE location;
TRUNCATE entry;

INSERT INTO location (country) VALUES
('Aruba'),
('Afghanistan'),
('Angola'),
('Anguilla'),
('Albania'),
('Aland'),
('Andorra'),
('United Arab Emirates'),
('Argentina'),
('Armenia'),
('American Samoa'),
('Antarctica'),
('Ashmore and Cartier Islands'),
('French Southern and Antarctic Lands'),
('Antigua and Barbuda'),
('Australia'),
('Austria'),
('Azerbaijan'),
('Burundi'),
('Belgium'),
('Benin'),
('Burkina Faso'),
('Bangladesh'),
('Bulgaria'),
('Bahrain'),
('The Bahamas'),
('Bosnia and Herzegovina'),
('Bajo Nuevo Bank (Petrel Is)'),
('Saint Barthelemy'),
('Belarus'),
('Belize'),
('Bermuda'),
('Bolivia'),
('Brazil'),
('Barbados'),
('Brunei'),
('Bhutan'),
('Botswana'),
('Central African Republic'),
('Canada'),
('Switzerland'),
('Chile'),
('China'),
('Ivory Coast'),
('Clipperton Island'),
('Cameroon'),
('Cyprus No Mans Area'),
('Democratic Republic of the Congo'),
('Republic of Congo'),
('Cook Islands'),
('Colombia'),
('Comoros'),
('Cape Verde'),
('Costa Rica'),
('Coral Sea Islands'),
('Cuba'),
('Curacao'),
('Cayman Islands'),
('Northern Cyprus'),
('Cyprus'),
('Czech Republic'),
('Germany'),
('Djibouti'),
('Dominica'),
('Denmark'),
('Dominican Republic'),
('Algeria'),
('Ecuador'),
('Egypt'),
('Eritrea'),
('Dhekelia Sovereign Base Area'),
('Spain'),
('Estonia'),
('Ethiopia'),
('Finland'),
('Fiji'),
('Falkland Islands'),
('France'),
('Faroe Islands'),
('Federated States of Micronesia'),
('Gabon'),
('United Kingdom'),
('Georgia'),
('Guernsey'),
('Ghana'),
('Gibraltar'),
('Guinea'),
('Gambia'),
('Guinea Bissau'),
('Equatorial Guinea'),
('Greece'),
('Grenada'),
('Greenland'),
('Guatemala'),
('Guam'),
('Guyana'),
('Hong Kong S.A.R.'),
('Heard Island and Mcdonald Island'),
('Honduras'),
('Croatia'),
('Haiti'),
('Hungary'),
('Indonesia'),
('Isle of Man'),
('India'),
('Indian Ocean Territory'),
('British Indian Ocean Territory'),
('Ireland'),
('Iran'),
('Iraq'),
('Iceland'),
('Israel'),
('Italy'),
('Jamaica'),
('Jersey'),
('Jordan'),
('Japan'),
('Baykonur Cosmodrone'),
('Siachen Glacier'),
('Kazakhstan'),
('Kenya'),
('Kyrgyzstan'),
('Cambodia'),
('Kiribati'),
('Saint Kitts and Nevis'),
('South Korea'),
('Kosovo'),
('Kuwait'),
('Laos'),
('Lebanon'),
('Liberia'),
('Libya'),
('Saint Lucia'),
('Liechtenstein'),
('Sri Lanka'),
('Lesotho'),
('Lithuania'),
('Luxembourg'),
('Latvia'),
('Macao S.A.R.'),
('Saint Martin'),
('Morocco'),
('Monaco'),
('Moldova'),
('Madagascar'),
('Maldives'),
('Mexico'),
('Marshall Islands'),
('Macedonia'),
('Mali'),
('Malta'),
('Myanmar'),
('Montenegro'),
('Mongolia'),
('Northern Mariana Islands'),
('Mozambique'),
('Mauritania'),
('Montserrat'),
('Mauritius'),
('Malawi'),
('Malaysia'),
('Namibia'),
('New Caledonia'),
('Niger'),
('Norfolk Island'),
('Nigeria'),
('Nicaragua'),
('Niue'),
('Netherlands'),
('Norway'),
('Nepal'),
('Nauru'),
('New Zealand'),
('Oman'),
('Pakistan'),
('Panama'),
('Pitcairn Islands'),
('Peru'),
('Spratly Islands'),
('Philippines'),
('Palau'),
('Papua New Guinea'),
('Poland'),
('Puerto Rico'),
('North Korea'),
('Portugal'),
('Paraguay'),
('Palestine'),
('French Polynesia'),
('Qatar'),
('Romania'),
('Russia'),
('Rwanda'),
('Western Sahara'),
('Saudi Arabia'),
('Scarborough Reef'),
('Sudan'),
('South Sudan'),
('Senegal'),
('Serranilla Bank'),
('Singapore'),
('South Georgie and South Sandwich Islands'),
('Saint Helena'),
('Solomon Islands'),
('Sierra Leone'),
('El Salvador'),
('San Marino'),
('Somaliland'),
('Somalia'),
('Saint Pierre and Miquelon'),
('Republic of Serbia'),
('Sao Tome and Principe'),
('Suriname'),
('Slovakia'),
('Slovenia'),
('Sweden'),
('Swaziland'),
('Sint Maartan'),
('Seychelles'),
('Syria'),
('Turks and Caicos Islands'),
('Chad'),
('Togo'),
('Thailand'),
('Tajikistan'),
('Turkmenistan'),
('East Timor'),
('Tonga'),
('Trinidad and Tobago'),
('Tunisia'),
('Turkey'),
('Tuvalu'),
('Taiwan'),
('United Republic of Tanzania'),
('Uganda'),
('Ukraine'),
('United States Minor Outlying Islands'),
('Uruguay'),
('United States of America'),
('US Naval Base Guantanamo Bay'),
('Uzbekistan'),
('Vatican'),
('Saint Vincent and the Grenadines'),
('Venezuela'),
('British Virgin Islands'),
('United States Virgin Islands'),
('Vietnam'),
('Vanuatu'),
('Wallis and Futuna'),
('Akrotiri Sovereign Base Area'),
('Samoa'),
('Yemen'),
('South Africa'),
('Zambia'),
('Zimbabwe');

INSERT INTO disease (description, name, preventions, symptoms, transmission, treatments) VALUES
('Coronaviruses (CoV) are a large family of viruses the can cause illness ranging from common cold to more severe diseases such as Middle East Respiratory Syndrome (MERS) and Severe Acute Respiratory Syndrome (SARS). The novel coronavirus (nCoV) is a new strain of coronavirus that has not been previously identified in humans. The virus is zoonotic, meaning they are transmitted between animals and people. The first outbreak was reported in Wuhan, China in December 2019. As this virus has only recently been reported, the amount of information about this specific strain is limited.', 'Novel Coronavirus', 'The main protection that one can do for the nCoV is to avoid contact with anyone who has the symptoms of nCoV. Washing hands frequently with soap and water or using an alcohol-based sanitizer is good practice in order to eliminate the virus if it is on your hands. The proper use of medical masks can help limit the spread of some respiratory disease but does not guaranteed prevention. Anyone who has travelled to China or has been in close contact with anyone that has should report to their health care provider if they have any respiratory symptoms.', 'The symptoms of the nCoV can vary from person to person. Some who are infected only display mild symptoms such as runny nose, sore throat, coughing, or fever. Others have ended up developing diseases like MERS. SARS, or pneumonia. In rarer cases, nCoV can be fatal. Those who are older or have pre-existing medical conditions appear to be more vulnerable to becoming severely ill.', 'The nCoV causes respiratory disease and can be transmitted from person to person from close contact. It can spread through respiratory droplets from coughing or sneezing. Those who have been in or travelled from China can possibly be carriers of the virus. The incubation period or the time between infection and the onset of symptoms can be up to 14 days.', 'As of date, there is no specific medicine that will prevent or treat the nCoV. Those who are infected should receive appropriate care to relieve and create symptoms. Those that are not infected should take care to avoid contact with those displaying symptoms.'),
('Ebola virus disease is a severe, often fatal illness which affect humans and other primates. The first case of Ebola appeared in 1976 in 2 simultaneous outbreaks, one in Nzara, South Sudan, and the other in Yambuku, DRC at a village near the Ebola River. It has an average case fatality rate of around 50%. In some outbreaks, the fatality rate have even risen to 90%. ', 'Ebola Virus Disease', 'Good outbreak control relies on case management, surveillance and contact tracing, raising awareness, and doing safe burials. All animals should be handled with proper protective clothing and should be cooked thoroughly before consuming. Anyone exhibiting Ebola symptoms should report to their health care provider for immediate treatments. Those who are in contact with infected should wear the proper protective clothing and should frequently wash hands. Burial should be handled by trained burial teams who can properly bury the dead safely and with dignity.', 'The Ebola virus disease can vary, but there are those that are commonly experienced at the beginning of the disease which is known as the “dry phase”. These symptoms include fever, intense weakness, muscle pain, headache, and sore throat. As the disease progresses into the “wet phase”, the symptoms become more severe with vomiting, diarrhea, rashes, impaired kidney and liver functions, and in some cases, both internal and external bleeding. ', 'People can become infected with Ebola either through contact with infected animals or contact with bodily fluids of infected humans. Infection can occur if the broken skin or the mucous membranes of a healthy person comes into contact with items or environments that are contaminated. This my include soiled clothing bed linen, gloves, protective equipment, and medical waste. Those who are at higher risk of infection are health workers, family members coming into close contact, and mourners who have direct contact with bodies during burial. The incubation period or the time between infection and the onset of symptoms can range from 2 to 21 days. It is also thought that the fruit bats of the Pteropodidae family are natural Ebola virus hosts.', 'While there is no proven treatment for Ebola disease, there are a range pot potential treatments including blood products, immune therapies, and drug therapies that are currently being evaluated. There is also an experimental vaccine that went through major trials in Guinea. This rVSV-ZEBOV vaccine is being used in the ongoing Ebola outbreak in the Democratic Republic of theCongo. '),
('Malaria is a life-threatening disease caused by Plasmodium parasites which are transmitted to people through the bites of infected female Anopheles mosquitoes. There are 5 different parasite species that causes malaria in humans, but 2 of the species pose the greatest threat: P. falciparum and P. vivax. The highest number of malaria cases and deaths occur in the African region, but a near hundred is are affected by malaria. While it is highly dangerous, it is preventable and curable. ','Malaria','Vector control is the main way to prevent and reduce malaria transmission. The use of insecticide-treated nets and indoor residual spraying with insecticides are both powerful methods in order to prevent mosquito bites. There are antimalarial medicines that can be used to prevent malaria. People can also undergo chemoprophylaxis which suppresses the blood stage of malaria infections. ','The first sign of symptoms are fevers, headaches, and chills which may be mild and difficult to recognize as malaria. If not treated, it can lead to sever illness or even death. Children frequently develop severe anaemia, respiratory distress, or cerebral malaria while adults frequently can get multi-organ failure. ','The main method of transmission for malaria is through the bites of the female Anopheles mosquitoes. Out of the 400 different species of Anopheles mosquito; around 30 are malaria vectors which mainly bite between dusk and dawn. The mosquitoes lay their eggs in water, so climate can play a huge factor on the population of mosquitoes. The incubation period or the time between infection and the onset of symptoms is around 10-15 days after the infective mosquito bite. ','While malaria is treatable, it must be done as early as possible to reduce disease and prevent deaths. The best available treatment is artemisinin-based combination therapy. Anyone who has suspected malaria should be confirmed using parasite-based diagnostic testing which can be available quickly. There is also a  vaccine being developed that can significantly reduce malaria in Africa. ');

INSERT INTO news(date, imageurl, link, summary, title, disease_id, location_id) VALUES
('2020-02-11','https://cdn.i-scmp.com/sites/default/files/styles/768x768/public/d8/images/methode/2020/01/28/7e1ba00e-40ea-11ea-9fd9-ecfbb38a9743_image_hires_045309.JPG?itok=5qaNEmxW&v=1580158396','https://www.washingtonpost.com/world/asia_pacific/coronavirus-china-live-updates/2020/02/10/67115416-4b9a-11ea-bf44-f5043eb3918a_story.html','As of early February 2020, tens of thousands of people worldwide were infected with a new strain of coronavirus.','Coronavirus updates: Global death toll passes 1,000 as China records most deaths in a single day',1,43),
('2020-02-11','https://www.washingtonpost.com/wp-apps/imrs.php?src=https://arc-anglerfish-washpost-prod-washpost.s3.amazonaws.com/public/BBLB4ECM2YI6VNZBT5GNZEF4DQ.jpg&w=1440','https://www.washingtonpost.com/world/dream-job-turns-into-nightmare-virus-fears-grow-among-diamond-princess-crew/2020/02/11/e65b54e8-4cca-11ea-967b-e074d302c7d4_story.html','Virus fears grow among Diamond Princess crew','‘Dream job’ turns into ‘nightmare’',1,117);
# ('2020-02-11',)
                                                                                       ;
INSERT INTO entry (date, new_cases, new_deaths, total_cases, total_deaths, disease_id, location_id) VALUES
();
